# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [3]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
#%pip install --upgrade selenium
#%pip install webdriver-manager

#### Passo 2: Importar bibliotecas

In [4]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys

#### Passo 3: Criar navegador

In [5]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome

#### Passo 4: Acessar site

In [6]:
# url: 'https://pubmed.ncbi.nlm.nih.gov/

driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed

#### Passo 5: Fechar navegador

In [7]:
driver.quit()

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [8]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome
driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed

#### 6.2: Selecionar o campo de busca pelo id

In [9]:
campo_busca = driver.find_element(By.ID, 'id_term')  # Localiza o campo de busca pelo ID

#### 6.3: Escrever um texto no campo de busca

In [10]:
campo_busca.send_keys('Pokemon')

#### 6.4: Clicar no Botão Pesquisar

In [11]:
driver.find_element(By.CLASS_NAME,'search-btn').click()  # Localiza o botão de busca pelo nome da classe e clica nele

#### 6.5: Fechar navegador

In [12]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [72]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome
driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed
campo_busca = driver.find_element(By.ID, 'id_term')  # Localiza o campo de busca pelo ID
campo_busca.send_keys('Pokemon', Keys.ENTER)  # Digita "Pokemon" no campo de busca e pressiona Enter
resultado = driver.find_elements(By.CLASS_NAME, 'docsum-content')  # Localiza o elemento que contém os resultados da busca
print("total de resultados: ", len(resultado))  # Imprime o texto do elemento que contém os resultados da busca

total de resultados:  10

#### 7.1: Listar o título de todos os resultados

In [38]:
lista_de_titulos = []

for i in resultado:
    lista_de_titulos.append(i.find_element(By.CLASS_NAME, 'docsum-title').text)  # Adiciona o texto do elemento que contém os resultados da busca à lista de títulos
lista_de_titulos

['Primary Care: Its Pokemon Moment.',
 'Impact of Pokemon Go on Physical Activity: A Systematic Review and Meta-Analysis.',
 'Effects of Pokemon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review.',
 'Influence of Pokemon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review.',
 'Going Forward with Pokemon Go.',
 'Pokemon contagion.',
 'Random forests, sound symbolism and Pokemon evolution.',
 'Pokemon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians.',
 'Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms.',
 'Pokemon GO and Physical Activity in Asia: Multilevel Study.']

#### 7.2: Listar o link de todos os resultados

In [73]:
lista_de_links = []

for j in resultado:
    lista_de_links.append(j.find_element(By.CLASS_NAME, 'docsum-title').get_attribute('href'))
lista_de_links

['https://pubmed.ncbi.nlm.nih.gov/38556037/',
 'https://pubmed.ncbi.nlm.nih.gov/31836333/',
 'https://pubmed.ncbi.nlm.nih.gov/33922978/',
 'https://pubmed.ncbi.nlm.nih.gov/37955949/',
 'https://pubmed.ncbi.nlm.nih.gov/30568365/',
 'https://pubmed.ncbi.nlm.nih.gov/11811868/',
 'https://pubmed.ncbi.nlm.nih.gov/36598905/',
 'https://pubmed.ncbi.nlm.nih.gov/27479151/',
 'https://pubmed.ncbi.nlm.nih.gov/39095579/',
 'https://pubmed.ncbi.nlm.nih.gov/29907559/']

#### 7.3: Acessar um dos links

In [75]:
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

##### 1) Título

In [76]:
titulo = driver.find_element(By.CLASS_NAME, 'heading-title').text
print(titulo)

Primary Care: Its Pokemon Moment

##### 2) Autores

In [42]:
autor = driver.find_element(By.CLASS_NAME, 'full-name').text
print(autor)

Bryan Becker

##### 3) Ano de publicação

In [43]:
ano_publicacao = driver.find_element(By.CLASS_NAME, 'secondary-date').text
print(ano_publicacao)

Epub 2024 Mar 29.

##### 4) DOI

In [44]:
DOI = driver.find_element(By.CLASS_NAME, 'identifier.doi').text
print(DOI)

DOI: 10.1016/j.amjmed.2024.03.020

##### 5) Tipo de publicação

In [45]:
tipo_publicacao = driver.find_element(By.CLASS_NAME, 'publication-type').text
print(tipo_publicacao)

Review

##### 6) Resumo

In [46]:
resumo = driver.find_element(By.CLASS_NAME, 'abstract-content.selected').text
print(resumo)

Primary care in the United States is undergoing bursts of evolution in response to health system stresses, changing demographics, and expansion of risk and value-based reimbursement structures. The impact of primary care remains substantive and associated with improved population health. However, the spectrum of services, the nature of the physicians involved and new ways of including the patient in her, or his own care suggests that a new definition of primary care be considered, and patient expectations be heeded and understood. Evolutionary bursts yield new traits and in primary care, they are spawning new care models with significant implications for general internal medicine, internal medicine/pediatrics trained individuals and medicine subspecialties given the focus of these models on Medicare Advantage. Ultimately, changes in reimbursement and creative incentives will be two factors among many that will solidify the next stage of primary care in the United States.

##### 7) Link de acesso (como registro de referência)

In [24]:
link_deacesso = driver.find_element(By.CLASS_NAME, 'link-item').get_attribute('href')
print(link_deacesso)

https://linkinghub.elsevier.com/retrieve/pii/S0002-9343(24)00166-9

In [49]:
dados = [
    'titulo',
    'autor',
    'ano_publicacao',
    'DOI',
    'tipo_publicacao',
    'resumo' ,
    'link_deacesso'
]

df = pd.DataFrame(columns=dados)
df.head()

Empty DataFrame
Columns: [titulo, autor, ano_publicacao, DOI, tipo_publicacao, resumo, link_deacesso]
Index: []

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [89]:
dados = [
    'titulo',
    'autor',
    'ano_publicacao',
    'DOI',
    'tipo_publicacao',
    'resumo' ,
    'link_deacesso'
]

df = pd.DataFrame(columns=dados)
df.head()

Empty DataFrame
Columns: [titulo, autor, ano_publicacao, DOI, tipo_publicacao, resumo, link_deacesso]
Index: []

#### 2) Obter dados dos links e armazenar na tabela

In [90]:
import time
for i in lista_de_links:
    driver.get(i)
    time.sleep(2)  # Aguarda 2 segundos para a página carregar
    try:
        titulo = driver.find_element(By.CLASS_NAME, 'heading-title').text
        print(titulo)
    except:
        print("Não foi possível localizar o título do artigo")
        titulo = None
    try:
        autor = driver.find_element(By.CLASS_NAME, 'full-name').text
    except:
        autor = None
    try:
        ano_publicacao = driver.find_element(By.CLASS_NAME, 'secondary-date').text 
    except:
        ano_publicacao = None
    try:
        DOI = driver.find_element(By.CLASS_NAME, 'identifier.doi').text
    except:
        DOI = None
    try:
        tipo_publicacao = driver.find_element(By.CLASS_NAME, 'publication-type').text
    except:
        tipo_publicacao = None
    try:
        resumo = driver.find_element(By.CLASS_NAME, 'abstract-content.selected').text
    except:
        resumo = None
    try:
        link_deacesso = driver.find_element(By.CLASS_NAME, 'link-item').get_attribute('href')
    except:
        link_deacesso = None
    df = pd.concat([df, pd.DataFrame([[titulo, autor, ano_publicacao, DOI, tipo_publicacao, resumo, link_deacesso]], columns=dados)])
df.head(10)

Primary Care: Its Pokemon Moment
Impact of Pokémon Go on Physical Activity: A Systematic Review and Meta-Analysis
Effects of Pokémon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review
Influence of Pokémon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review
Going Forward with Pokemon Go
Pokemon contagion
Random forests, sound symbolism and Pokémon evolution
Pokémon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians
Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms
Pokémon GO and Physical Activity in Asia: Multilevel Study

,titulo,autor,ano_publicacao,DOI,tipo_publicacao,resumo,link_deacesso
0,Primary Care: Its Pokemon Moment,Bryan Becker,Epub 2024 Mar 29.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...,https://linkinghub.elsevier.com/retrieve/pii/S...
0,Impact of Pokémon Go on Physical Activity: A S...,Madina Khamzina,Epub 2019 Dec 10.,DOI: 10.1016/j.amepre.2019.09.005,Meta-Analysis,Context: Pokémon Go is a popular mobile augmen...,https://linkinghub.elsevier.com/retrieve/pii/S...
0,Effects of Pokémon GO on Physical Activity and...,Jung Eun Lee,None,DOI: 10.3390/jcm10091860,Review,"Augmented reality (AR) mobile game, Pokémon GO...",https://www.mdpi.com/resolver?pii=jcm10091860
0,Influence of Pokémon GO on Physical Activity a...,Haiyan Liang,None,DOI: 10.2196/49019,Review.,"Background: Pokémon GO, an augmented reality g...",https://www.jmir.org/2023//e49019/
0,Going Forward with Pokemon Go,Yvette Chong,None,DOI: 10.4103/JETS.JETS_87_17,Review,Pokemon Go is an augmented reality (AR) game w...,http://www.onlinejets.org/article.asp?issn=097...
0,Pokemon contagion,B G Zifkin,None,DOI: 10.1097/00007611-200112000-00025,Comment,None,https://pubmed.ncbi.nlm.nih.gov/11811868/#
0,"Random forests, sound symbolism and Pokémon ev...",Alexander James Kilpatrick,eCollection 2023.,DOI: 10.1371/journal.pone.0279350,Review.,This study constructs machine learning algorit...,https://dx.plos.org/10.1371/journal.pone.0279350
0,Pokémon Go and augmented virtual reality games...,Maeve Serino,None,DOI: 10.1097/MOP.0000000000000409,Review,Purpose of review: The recent release of Pokém...,https://www.ovid.com/10.1097/MOP.0000000000000409
0,Pokemon inhibits Bim transcription to promote ...,Yan Wang,None,DOI: 10.1007/s00432-024-05904-1,None,Purpose: This study aims to determine whether ...,https://dx.doi.org/10.1007/s00432-024-05904-1
0,Pokémon GO and Physical Activity in Asia: Mult...,Ben D Ma,None,DOI: 10.2196/jmir.9670,Review.,Background: Physical activity has long been co...,https://www.jmir.org/2018/6/e217/

#### 3) Visualizar tabela

In [87]:
df.head(10)

,titulo,autor,ano_publicacao,DOI,tipo_publicacao,resumo,link_deacesso
0,Primary Care: Its Pokemon Moment,Bryan Becker,Epub 2024 Mar 29.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...,https://linkinghub.elsevier.com/retrieve/pii/S...
0,Impact of Pokémon Go on Physical Activity: A S...,Madina Khamzina,Epub 2019 Dec 10.,DOI: 10.1016/j.amepre.2019.09.005,Meta-Analysis,Context: Pokémon Go is a popular mobile augmen...,https://linkinghub.elsevier.com/retrieve/pii/S...
0,Effects of Pokémon GO on Physical Activity and...,Jung Eun Lee,None,DOI: 10.3390/jcm10091860,Review,"Augmented reality (AR) mobile game, Pokémon GO...",https://www.mdpi.com/resolver?pii=jcm10091860
0,Influence of Pokémon GO on Physical Activity a...,Haiyan Liang,None,DOI: 10.2196/49019,Review.,"Background: Pokémon GO, an augmented reality g...",https://www.jmir.org/2023//e49019/
0,Going Forward with Pokemon Go,Yvette Chong,None,DOI: 10.4103/JETS.JETS_87_17,Review,Pokemon Go is an augmented reality (AR) game w...,http://www.onlinejets.org/article.asp?issn=097...
0,Pokemon contagion,B G Zifkin,None,DOI: 10.1097/00007611-200112000-00025,Comment,None,https://pubmed.ncbi.nlm.nih.gov/11811868/#
0,"Random forests, sound symbolism and Pokémon ev...",Alexander James Kilpatrick,eCollection 2023.,DOI: 10.1371/journal.pone.0279350,Review.,This study constructs machine learning algorit...,https://dx.plos.org/10.1371/journal.pone.0279350
0,Pokémon Go and augmented virtual reality games...,Maeve Serino,None,DOI: 10.1097/MOP.0000000000000409,Review,Purpose of review: The recent release of Pokém...,https://www.ovid.com/10.1097/MOP.0000000000000409
0,Pokemon inhibits Bim transcription to promote ...,Yan Wang,None,DOI: 10.1007/s00432-024-05904-1,None,Purpose: This study aims to determine whether ...,https://dx.doi.org/10.1007/s00432-024-05904-1
0,Pokémon GO and Physical Activity in Asia: Mult...,Ben D Ma,None,DOI: 10.2196/jmir.9670,Review.,Background: Physical activity has long been co...,https://www.jmir.org/2018/6/e217/

#### 4) Exportar DataFrame para Excel

In [91]:
df.to_csv(
    "raspagem_site.csv",
    index=False
)